const langState={lang:localStorage.getItem("chemnorm-lang")||"en"};const state={products:[],filtered:[],page:1,size:18};const $=s=>document.querySelector(s);const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const clean=s=>String(s||'').replace(/\s+Inquiry Product introduction.*$/i,'').trim();const trim=(s,n)=>{s=clean(s);return s.length>n?s.slice(0,n).trim()+'…':s};const valid=s=>Boolean(s)&&!/[\\uFFFD\\u00A0]/.test(String(s));
async function init(){const res=await fetch('./data/chemnorm/products.json',{cache:'no-store'});if(!res.ok)throw Error('Product data request failed: '+res.status);state.products=await res.json();$('#heroCount').textContent=state.products.length.toLocaleString();const cats=[...new Set(state.products.map(p=>p.category).filter(valid))].sort();$('#cat').innerHTML+=cats.map(c=>`<option>${esc(c)}</option>`).join('');const q=$('#q'),box=q.closest('.search-box'),hint=box.querySelector('kbd'),btn=document.createElement('button');btn.type='button';btn.id='searchBtn';btn.textContent='Search';hint.replaceWith(btn);let timer;q.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(filter,180)});q.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();clearTimeout(timer);filter();$('#catalog').scrollIntoView({behavior:'smooth'})}});btn.addEventListener('click',()=>{clearTimeout(timer);filter();$('#catalog').scrollIntoView({behavior:'smooth'})});$('#cat').addEventListener('change',filter);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();q.focus()}});filter()}
function filter(){const q=$('#q').value.toLowerCase().trim(),c=$('#cat').value;state.filtered=state.products.filter(p=>(!q||[p.title,p.cas,p.product_no,p.alias,p.category].join(' ').toLowerCase().includes(q))&&(!c||p.category===c));state.page=1;draw()}
function card(p){const id=Number.isInteger(p._catalogIndex)?p._catalogIndex:state.products.indexOf(p),key=p.product_no||p.cas||p.title,img=p.structure_image||'',spec=[p.formula&&['Formula',p.formula],p.purity&&['Purity',p.purity]].filter(Boolean);return `<article class="product-card compact-card"><a class="structure-thumb" href="product.html?id=${id}">${img?`<img loading="lazy" src="${esc(img)}" alt="${esc(langState.lang==="zh"?(p.title_zh||p.title+"（中文名待补充）"):p.title)} chemical structure" onerror="this.remove();this.parentElement.classList.add('no-structure')">`:''}<span class="formula-mark">${esc(p.formula||'CN')}</span></a><div class="compact-body"><div class="card-top"><span class="compound-no">${esc(p.product_no||'Reference standard')}</span><span class="status-dot">${langState.lang==="zh"?"仅限科研":"Research use"}</span></div><h3><a href="product.html?id=${id}">${esc(langState.lang==="zh"?(p.title_zh||p.title+"（中文名待补充）"):p.title)}</a></h3><div class="cas">CAS <b>${esc(p.cas||'Not listed')}</b></div><div class="compact-meta">${p.category?`<span class="class-pill">${esc(p.category)}</span>`:''}${spec.map(([k,v])=>`<span><small>${k}</small>${esc(trim(v,30))}</span>`).join('')}</div><div class="commerce-actions"><a class="view-link" href="product.html?id=${id}">${langState.lang==="zh"?"查看详情":"View details"} <span>→</span></a><button type="button" data-inquiry-key="${esc(key)}">${langState.lang==="zh"?"加入询价":"Add to inquiry"}</button></div></div></article>`}
function draw(){const rows=state.filtered.slice((state.page-1)*state.size,state.page*state.size);$('#count').innerHTML=`<b>${state.filtered.length.toLocaleString()}</b> ${langState.lang==="zh"?"个产品":"compounds found"}`;$('#grid').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">No matching ${langState.lang==="zh"?"个产品":"compounds found"}.</div>';const total=Math.ceil(state.filtered.length/state.size),start=Math.max(1,Math.min(state.page-3,total-6));$('#pages').innerHTML=Array.from({length:Math.min(total,7)},(_,i)=>{const p=start+i;return `<button class="${p===state.page?'active':''}" data-page="${p}">${p}</button>`}).join('');$('#pages').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.page=+b.dataset.page;draw();$('#catalog').scrollIntoView({behavior:'smooth'})})}
init().catch(e=>{$('#grid').innerHTML='<div class="empty">The product database could not be loaded. Refresh the page to try again.</div>';console.error(e)});
function addInquiry(id){const key='chemnorm-inquiry',items=JSON.parse(localStorage.getItem(key)||'[]');if(!items.includes(id))items.push(id);localStorage.setItem(key,JSON.stringify(items));}
document.addEventListener('click',e=>{const b=e.target.closest('[data-inquiry-key]');if(b){e.preventDefault();addInquiry(b.dataset.inquiryKey);location.href='inquiry.html?key='+encodeURIComponent(b.dataset.inquiryKey)}});





const translations={en:{catalog:'Catalog',capabilities:'Capabilities',quote:'Request a quote',database:'PRODUCT DATABASE',explore:'Explore reference standards',filter:'Filter the catalog and open a compound record for available specifications.',contact:'Contact our team →'},zh:{catalog:'产品目录',capabilities:'服务能力',quote:'获取报价',database:'产品数据库',explore:'探索天然产物标准品',filter:'浏览产品目录，查看规格并提交批量询价。',contact:'联系我们 →'}};function applyLanguage(lang){langState.lang=lang;const t=translations[lang]||translations.en;const nav=[...document.querySelectorAll('.topbar nav a')];if(nav[0])nav[0].textContent=t.catalog;if(nav[1])nav[1].textContent=t.capabilities;if(nav[2])nav[2].textContent=t.quote;const k=[...document.querySelectorAll('.catalog-head .kicker')][0];if(k)k.lastChild.textContent=t.database;const h=document.querySelector('.catalog-head h2');if(h)h.textContent=t.explore;const p=document.querySelector('.catalog-head p');if(p)p.textContent=t.filter;const c=document.querySelector('.quality>a');if(c)c.textContent=t.contact;localStorage.setItem('chemnorm-lang',lang);if(typeof draw==='function')draw()}document.addEventListener('change',e=>{if(e.target.id==='language')applyLanguage(e.target.value)});document.addEventListener('DOMContentLoaded',()=>applyLanguage(localStorage.getItem('chemnorm-lang')||'en'));








