(async function(){
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const params=new URLSearchParams(location.search),key=params.get('key'),idParam=params.get('id');
  const productField=document.getElementById('product'),identifierField=document.getElementById('identifier'),card=document.getElementById('inquiryProduct');let current=null;
  try{const data=await(await fetch('data/chemnorm/products.json',{cache:'no-store'})).json();current=key?data.find(x=>String(x.product_no||'').trim()===String(key).trim()):idParam!==null?data[Number(idParam)]:null;if(current){productField.value=current.title||'';identifierField.value=(current.cas||'')+' / '+(current.product_no||'');card.innerHTML=`${current.structure_image?`<img src="${esc(current.structure_image)}" alt="${esc(current.title)} molecular structure">`:''}<h2>${esc(current.title||'Selected product')}</h2><p>CAS: ${esc(current.cas||'Not listed')}</p><p>Product ID: ${esc(current.product_no||'Not listed')}</p>`;const related=data.filter(x=>x!==current&&current.category&&x.category===current.category).slice(0,3);document.getElementById('relatedProducts').innerHTML=related.map(x=>{const k=x.product_no||x.cas||x.title;return `<article class="related-inquiry-card">${x.structure_image?`<img src="${esc(x.structure_image)}" alt="${esc(x.title)} molecular structure">`:`<div class="related-no-image">${esc(x.formula||'Structure unavailable')}</div>`}<div><span>${esc(x.product_no||'Reference standard')}</span><h3>${esc(x.title||'Compound')}</h3><p>CAS ${esc(x.cas||'Not listed')}</p><small>${esc(x.formula||'Formula unavailable')}</small><a href="inquiry.html?key=${encodeURIComponent(k)}">Inquire 鈫?/a></div></article>`}).join('')}else{card.innerHTML='<h2>General inquiry</h2><p>Tell us which product you need.</p>';productField.value=params.get('product')||'General inquiry';identifierField.value=params.get('identifier')||''}}catch(e){card.innerHTML='<h2>Product inquiry</h2><p>Product details remain attached to your request.</p>';productField.value=params.get('product')||'Product inquiry';identifierField.value=params.get('identifier')||''}
  const form=document.querySelector('form'),button=form.querySelector('button[type=submit]'),status=document.getElementById('form-status');
  form.addEventListener('submit',async event=>{event.preventDefault();button.disabled=true;button.textContent='Sending...';status.textContent='';try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw Error('HTTP '+response.status);location.assign('inquiry-success.html?product='+encodeURIComponent(productField.value)+'&identifier='+encodeURIComponent(identifierField.value)+'&brief='+encodeURIComponent(form.elements.message.value)+'&key='+encodeURIComponent(key||''))}catch(error){status.textContent='Unable to send ('+(error.message||'network error')+'). Please try again or email w459292219@gmail.com.';button.disabled=false;button.textContent='Send inquiry ->'}});
})();

