const fs = require('fs');
const root = 'D:/pyproject/chemnorm';
const zh = root + '/zh';
fs.mkdirSync(zh, { recursive: true });

const page = (title, body, scripts = '') => `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><link rel="stylesheet" href="site.css?v=zh2"><link rel="stylesheet" href="compact-cards.css?v=zh2"><link rel="stylesheet" href="inquiry.css?v=zh2"><link rel="stylesheet" href="product-visual.css?v=zh2"></head><body><header class="topbar"><a class="logo" href="index.html"><i>CN</i><span>CHEMNORM<small>天然产物标准品</small></span></a><nav><label class="language-switch">语言 <select id="siteLanguage"><option value="zh">中文</option><option value="en">English</option></select></label><a href="index.html#catalog">产品目录</a><a href="index.html#capabilities">服务能力</a><a href="contact.html">联系我们</a></nav></header>${body}<footer><a class="logo" href="index.html"><i>CN</i><span>CHEMNORM<small>天然产物标准品</small></span></a><p>天然产物标准品，仅限科研与实验室使用。</p><span>© 2026 ChemNorm</span></footer>${scripts}<script src="../language-switch.js?v=lang1"></script></body></html>`;

const home = `<main><section class="hero"><div class="hero-copy"><div class="kicker"><span></span>天然产物标准品</div><h1>为天然产物研究提供<br><em>精准可靠的标准品。</em></h1><p>浏览结构化的植物化学成分与标准化合物数据库，通过产品名称、CAS 号、产品编号及分子数据快速检索。</p><div class="search-box"><input id="q" autocomplete="off" placeholder="搜索英文名、中文名、CAS 号或产品编号"><button id="searchBtn" type="button">搜索</button></div><div class="trust"><span><b id="heroCount">10,197+</b> 种化合物</span><span><b>19</b> 个化学分类</span><span><b>HPLC</b> 规格数据</span></div></div><div class="molecule" aria-hidden="true"><div class="orbit o1"></div><div class="orbit o2"></div><div class="core">C<small>28</small>H<small>32</small>O<small>15</small></div></div></section><section class="industry-visuals"><article class="visual-card lab-photo"><div><span>实验室分析</span><h3>从样品到标准化检测</h3></div></article><article class="visual-card vial-photo"><div><span>标准物质</span><h3>为每项检测提供可靠标准</h3></div></article><article class="visual-card reagent-photo"><div><span>化学试剂</span><h3>满足科研检测的高纯试剂</h3></div></article></section><section id="capabilities" class="proof"><article><div class="proof-icon">01</div><h3>多维度检索</h3><p>通过英文名、已核验中文名、别名、CAS 号和产品编号查找化合物。</p></article><article><div class="proof-icon">02</div><h3>科研规格信息</h3><p>查看分子式、分子量、纯度、外观和储存条件等资料。</p></article><article><div class="proof-icon">03</div><h3>询价支持</h3><p>获取当前批次文件、包装规格、供货情况及报价。</p></article></section><section id="catalog" class="catalog-head"><div><div class="kicker"><span></span>产品数据库</div><h2>浏览天然产物标准品</h2><p>筛选产品目录并查看化合物规格与详细资料。</p></div><div class="catalog-controls"><label>化学分类<select id="cat"><option value="">全部分类</option></select></label><div id="count" class="result-count">正在加载产品…</div></div></section><div id="grid" class="product-grid"><div class="loading">正在初始化产品目录…</div></div><div id="pages" class="pagination"></div><section id="quality" class="quality"><div><div class="kicker"><span></span>仅限科研使用</div><h2>结构化数据，清晰规格，高效检索。</h2></div><p>产品信息仅供科研与实验室使用。请联系 ChemNorm 确认当前批次规格、支持文件及供货情况。</p><a href="contact.html">联系我们 <span>→</span></a></section></main>`;
fs.writeFileSync(zh + '/index.html', page('ChemNorm | 天然产物标准品', home, '<script src="app-zh.js?v=zh1"></script>'));

const contact = `<main class="inquiry-wrap"><div class="inquiry-intro"><div class="kicker"><span></span>联系 CHEMNORM</div><h1>联系我们的团队</h1><p>我们为科研团队、分析实验室及经销商提供天然产物标准品、技术文件与定制需求支持。</p></div><section class="inquiry-form"><h2>公司信息</h2><p><b>Wuhan ChemNorm Technology Co., Ltd.</b></p><p>邮箱：<a href="mailto:w459292219@gmail.com">w459292219@gmail.com</a></p><p>如需查询供货情况、证书、包装规格或技术问题，请提交询价，并尽可能注明 CAS 号或产品编号。</p><a class="quote-btn" href="inquiry.html">提交产品询价 <span>→</span></a></section></main>`;
fs.writeFileSync(zh + '/contact.html', page('联系 ChemNorm', contact));

const inquiry = `<main class="minimal-inquiry"><section class="minimal-head"><div class="kicker"><span></span>产品询价</div><h1>获取产品信息</h1><p>填写简短需求，我们通常会在一个工作日内回复。</p></section><section class="minimal-panel"><div id="inquiryProduct" class="inquiry-product"><div class="loading">正在加载产品…</div></div><form class="minimal-form" action="https://formspree.io/f/mjybyrpr" method="POST"><input type="hidden" name="_subject" value="ChemNorm 产品询价"><input type="hidden" id="product" name="product"><input type="hidden" id="identifier" name="identifier"><label>工作邮箱 <span>*</span><input type="email" name="email" required placeholder="name@company.com"></label><label>您的需求 <span>*</span><textarea name="message" rows="4" required>请提供该产品的报价、供货情况、纯度、包装规格和交期。</textarea></label><div class="optional-row"><label>姓名 <small>选填</small><input name="name"></label><label>公司 / 机构 <small>选填</small><input name="organization"></label></div><div id="form-status" class="form-status"></div><button type="submit">提交询价 <span>→</span></button><p class="privacy">您的联系信息仅用于回复本次询价。</p></form></section></main><section class="related-inquiries"><div class="kicker"><span></span>相关产品</div><h2>您可能还感兴趣</h2><div id="relatedProducts" class="related-product-grid"></div></section>`;
fs.writeFileSync(zh + '/inquiry.html', page('产品询价 | ChemNorm', inquiry, '<script src="inquiry-zh.js?v=zh1"></script>'));
const success = `<main class="success-wrap"><section class="success-hero"><div class="success-check">✓</div><div class="kicker"><span></span>询价已收到</div><h1>感谢您，询价已成功提交。</h1><p>我们会通过邮件回复供货情况、当前批次信息与报价详情。</p><div class="success-actions"><a class="quote-btn" href="index.html#catalog">浏览更多产品</a><a href="contact.html">联系我们</a></div></section></main>`;
fs.writeFileSync(zh + '/inquiry-success.html', page('询价已收到 | ChemNorm', success));
const product = `<main id="productMain"><div class="loading">正在加载产品信息…</div></main>`;
fs.writeFileSync(zh + '/product.html', page('产品详情 | ChemNorm', product, '<script src="product-zh.js?v=zh1"></script>'));

for (const f of fs.readdirSync(root).filter(x => x.endsWith('.css'))) fs.copyFileSync(root + '/' + f, zh + '/' + f);

fs.writeFileSync(zh + '/app-zh.js', `const state={products:[],filtered:[],page:1,size:18};const $=s=>document.querySelector(s);const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const name=p=>p.title_zh?p.title+'（'+p.title_zh+'）':p.title;async function init(){const r=await fetch('../data/chemnorm/products.json',{cache:'no-store'});state.products=await r.json();state.products.forEach((p,i)=>p._id=i);$('#heroCount').textContent=state.products.length.toLocaleString();const cats=[...new Set(state.products.map(p=>p.category).filter(Boolean))].sort();$('#cat').innerHTML+=cats.map(c=>'<option>'+esc(c)+'</option>').join('');$('#q').addEventListener('input',filter);$('#searchBtn').addEventListener('click',filter);$('#cat').addEventListener('change',filter);filter()}function filter(){const q=$('#q').value.toLowerCase().trim(),c=$('#cat').value;state.filtered=state.products.filter(p=>(!q||[p.title,p.title_zh,p.cas,p.product_no,p.alias,p.category].join(' ').toLowerCase().includes(q))&&(!c||p.category===c));state.page=1;draw()}function card(p){const k=p.product_no||p.cas||p.title;return '<article class="product-card compact-card"><a class="structure-thumb" href="product.html?id='+p._id+'">'+(p.structure_image?'<img loading="lazy" src="../'+esc(p.structure_image)+'" alt="'+esc(name(p))+' 分子结构">':'')+'<span class="formula-mark">'+esc(p.formula||'CN')+'</span></a><div class="compact-body"><div class="card-top"><span class="compound-no">'+esc(p.product_no||'标准品')+'</span><span class="status-dot">仅限科研</span></div><h3><a href="product.html?id='+p._id+'">'+esc(name(p))+'</a></h3><div class="cas">CAS <b>'+esc(p.cas||'暂无')+'</b></div><div class="compact-meta">'+(p.category?'<span class="class-pill">'+esc(p.category)+'</span>':'')+(p.formula?'<span><small>分子式</small>'+esc(p.formula)+'</span>':'')+'</div><div class="commerce-actions"><a class="view-link" href="product.html?id='+p._id+'">查看详情 →</a><a href="inquiry.html?key='+encodeURIComponent(k)+'">加入询价</a></div></div></article>'}function draw(){const rows=state.filtered.slice((state.page-1)*state.size,state.page*state.size);$('#count').innerHTML='<b>'+state.filtered.length.toLocaleString()+'</b> 个产品';$('#grid').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">没有找到匹配的产品。</div>';const total=Math.ceil(state.filtered.length/state.size);$('#pages').innerHTML=Array.from({length:Math.min(total,7)},(_,i)=>'<button class="'+(i+1===state.page?'active':'')+'" data-page="'+(i+1)+'">'+(i+1)+'</button>').join('');$('#pages').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.page=+b.dataset.page;draw()})}init().catch(e=>{$('#grid').innerHTML='<div class="empty">产品数据库加载失败，请刷新页面重试。</div>';console.error(e)});`);

fs.writeFileSync(zh + '/inquiry-zh.js', `(async()=>{const e=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const q=new URLSearchParams(location.search),key=q.get('key'),data=await(await fetch('../data/chemnorm/products.json')).json(),p=data.find(x=>String(x.product_no||'')===key);const card=document.getElementById('inquiryProduct');if(p){document.getElementById('product').value=p.title;document.getElementById('identifier').value=(p.cas||'')+' / '+(p.product_no||'');card.innerHTML=(p.structure_image?'<img src="../'+e(p.structure_image)+'" alt="分子结构">':'')+'<h2>'+e(p.title_zh?p.title+'（'+p.title_zh+'）':p.title)+'</h2><p>CAS：'+e(p.cas||'暂无')+'</p><p>产品编号：'+e(p.product_no||'暂无')+'</p>';const rel=data.filter(x=>x!==p&&x.category===p.category).slice(0,3);document.getElementById('relatedProducts').innerHTML=rel.map(x=>'<article class="related-inquiry-card">'+(x.structure_image?'<img src="../'+e(x.structure_image)+'" alt="分子结构">':'<div class="related-no-image">暂无结构图</div>')+'<div class="related-card-body"><span>'+e(x.product_no||'标准品')+'</span><h3>'+e(x.title_zh?x.title+'（'+x.title_zh+'）':x.title)+'</h3><p>CAS '+e(x.cas||'暂无')+'</p><div class="related-card-foot"><small>'+e(x.formula||'暂无分子式')+'</small><a href="inquiry.html?key='+encodeURIComponent(x.product_no||x.cas)+'">询价 →</a></div></div></article>').join('')}const form=document.querySelector('form'),status=document.getElementById('form-status');form.addEventListener('submit',async ev=>{ev.preventDefault();const b=form.querySelector('button');b.disabled=true;b.textContent='正在提交…';try{const r=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!r.ok)throw Error(r.status);location.href='inquiry-success.html'}catch(err){status.textContent='提交失败，请重试或发送邮件至 w459292219@gmail.com';b.disabled=false;b.textContent='提交询价 →'}})})().catch(console.error);`);
fs.writeFileSync(zh + '/product-zh.js', `(async()=>{const e=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const data=await(await fetch('../data/chemnorm/products.json')).json(),id=Number(new URLSearchParams(location.search).get('id')),p=data[id];if(!p)throw Error('missing');const n=p.title_zh?p.title+'（'+p.title_zh+'）':p.title;const row=(k,v)=>v?'<div class="detail-row"><span>'+k+'</span><b>'+e(v)+'</b></div>':'';document.title=n+' | ChemNorm';document.getElementById('productMain').innerHTML='<div class="breadcrumb"><a href="index.html">首页</a><span>/</span><a href="index.html#catalog">产品</a><span>/</span>'+e(n)+'</div><section class="product-hero"><div class="visual-stack"><div class="structure-card structure-image-card">'+(p.structure_image?'<img src="../'+e(p.structure_image)+'" alt="'+e(n)+' 分子结构">':'')+'<span class="structure-label">分子结构</span></div><div class="formula-card"><div class="chem-mark">'+e(p.formula||'暂无')+'<small>分子式</small></div></div></div><div class="product-summary"><div class="kicker"><span></span>'+e(p.category||'天然产物')+'</div><h1>'+e(n)+'</h1><p>天然产物标准品，仅供科研与实验室使用。</p>'+row('CAS号',p.cas)+row('产品编号',p.product_no)+row('化学分类',p.category)+'<a class="quote-btn" href="inquiry.html?key='+encodeURIComponent(p.product_no||p.cas)+'">获取产品资料 →</a></div></section><section class="detail-layout"><div class="detail-content"><div class="detail-section"><h2>产品信息</h2>'+row('别名',p.alias)+row('分子式',p.formula)+row('分子量',p.molecular_weight)+row('纯度',p.purity)+row('外观',p.appearance)+row('储存条件',p.storage)+row('用途',p.application)+'</div></div><aside><h3>仅限科研使用</h3><p>下单前请确认当前批次规格、技术文件及供货情况。</p></aside></section>'})().catch(()=>document.getElementById('productMain').innerHTML='<div class="empty">该产品记录无法加载。</div>');`);
