(async function(){
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const params=new URLSearchParams(location.search),key=params.get('key'),idParam=params.get('id');
  const productField=document.getElementById('product'),identifierField=document.getElementById('identifier'),card=document.getElementById('inquiryProduct');let current=null;
  try{const data=await(await fetch('../data/chemnorm/products.json',{cache:'no-store'})).json();current=key?data.find(x=>String(x.product_no||'').trim()===String(key).trim()):idParam!==null?data[Number(idParam)]:null;if(current){productField.value=current.title||'';identifierField.value=(current.cas||'')+' / '+(current.product_no||'');card.innerHTML=`${current.structure_image?`<img src="../${esc(current.structure_image)}" alt="${esc(current.title)} molecular structure">`:''}<h2>${esc(current.title||'所选产品')}</h2><p>CAS: ${esc(current.cas||'暂无')}</p><p>Product ID: ${esc(current.product_no||'暂无')}</p>`;const related=data.filter(x=>x!==current&&current.category&&x.category===current.category).slice(0,3);document.getElementById('relatedProducts').innerHTML=related.map(x=>{const k=x.product_no||x.cas||x.title;return `<article class="related-inquiry-card">${x.structure_image?`<img src="../${esc(x.structure_image)}" alt="${esc(x.title)} molecular structure">`:`<div class="related-no-image">${esc(x.formula||'暂无结构图')}</div>`}<div class="related-card-body"><span>${esc(x.product_no||'标准品')}</span><h3>${esc(x.title||'化合物')}</h3><p>CAS ${esc(x.cas||'暂无')}</p><div class="related-card-foot"><small>${esc(x.formula||'暂无分子式')}</small><a href="inquiry.html?key=${encodeURIComponent(k)}">询价 <span aria-hidden="true">&rarr;</span></a></div></div></article>`}).join('')}else{card.innerHTML='<h2>一般询价</h2><p>请告诉我们您需要的产品。</p>';productField.value=params.get('product')||'一般询价';identifierField.value=params.get('identifier')||''}}catch(e){card.innerHTML='<h2>产品询价</h2><p>产品信息将随询价一起提交。</p>';productField.value=params.get('product')||'产品询价';identifierField.value=params.get('identifier')||''}
  const form=document.querySelector('form'),button=form.querySelector('button[type=submit]'),status=document.getElementById('form-status');
  form.addEventListener('submit',async event=>{event.preventDefault();button.disabled=true;button.textContent='正在提交…';status.textContent='';try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw Error('HTTP '+response.status);location.assign('inquiry-success.html?product='+encodeURIComponent(productField.value)+'&identifier='+encodeURIComponent(identifierField.value)+'&brief='+encodeURIComponent(form.elements.message.value)+'&key='+encodeURIComponent(key||''))}catch(error){status.textContent='提交失败 ('+(error.message||'network error')+'). 请重试或发送邮件至 w459292219@gmail.com.';button.disabled=false;button.textContent='提交询价 →'}});
})();



